// Code generated by mockery v2.10.0. DO NOT EDIT.

package accrualprocessor

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

// GetTasksToRun provides a mock function with given fields: ctx
func (_m *MockReader) GetTasksToRun(ctx context.Context) ([]*entity.ProcessingTask, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.ProcessingTask
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.ProcessingTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ProcessingTask)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
