// Code generated by mockery v2.10.0. DO NOT EDIT.

package accrual_processor

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"

	time "time"

	uuid "github.com/gofrs/uuid"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

// CleanProcessedTasks provides a mock function with given fields: ctx
func (_m *MockWriter) CleanProcessedTasks(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockWriter) CreateTask(ctx context.Context, task *entity.ProcessingTask) error {
	ret := _m.Called(ctx, task)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ProcessingTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTasks provides a mock function with given fields: ctx, tasks
func (_m *MockWriter) CreateTasks(ctx context.Context, tasks []*entity.ProcessingTask) error {
	ret := _m.Called(ctx, tasks)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.ProcessingTask) error); ok {
		r0 = rf(ctx, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RescheduleTask provides a mock function with given fields: ctx, taskId, nextRun
func (_m *MockWriter) RescheduleTask(ctx context.Context, taskId uuid.UUID, nextRun time.Time) error {
	ret := _m.Called(ctx, taskId, nextRun)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, taskId, nextRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTaskStatus provides a mock function with given fields: ctx, taskId, status
func (_m *MockWriter) SetTaskStatus(ctx context.Context, taskId uuid.UUID, status entity.ProcessingTaskStatus) error {
	ret := _m.Called(ctx, taskId, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.ProcessingTaskStatus) error); ok {
		r0 = rf(ctx, taskId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
