// Code generated by mockery v2.10.0. DO NOT EDIT.

package accrual_processor

import mock "github.com/stretchr/testify/mock"

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MockUseCase) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
