// Code generated by mockery v2.10.0. DO NOT EDIT.

package order

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, order
func (_m *MockWriter) Create(ctx context.Context, order entity.Order) (uuid.UUID, error) {
	ret := _m.Called(ctx, order)

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context, entity.Order) uuid.UUID); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetOrderAccrualAndStatus provides a mock function with given fields: ctx, orderID, accrual, status
func (_m *MockWriter) SetOrderAccrualAndStatus(ctx context.Context, orderID uuid.UUID, accrual decimal.NullDecimal, status entity.OrderStatus) error {
	ret := _m.Called(ctx, orderID, accrual, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.NullDecimal, entity.OrderStatus) error); ok {
		r0 = rf(ctx, orderID, accrual, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOrderStatus provides a mock function with given fields: ctx, orderID, status
func (_m *MockWriter) SetOrderStatus(ctx context.Context, orderID uuid.UUID, status entity.OrderStatus) error {
	ret := _m.Called(ctx, orderID, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.OrderStatus) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
