// Code generated by mockery v2.10.0. DO NOT EDIT.

package order

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, orderNumber, userID
func (_m *MockUseCase) CreateOrder(ctx context.Context, orderNumber entity.OrderNumber, userID uuid.UUID) (*entity.Order, error) {
	ret := _m.Called(ctx, orderNumber, userID)

	var r0 *entity.Order
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderNumber, uuid.UUID) *entity.Order); ok {
		r0 = rf(ctx, orderNumber, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderNumber, uuid.UUID) error); ok {
		r1 = rf(ctx, orderNumber, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccrualsSum provides a mock function with given fields: ctx, userID
func (_m *MockUseCase) GetAccrualsSum(ctx context.Context, userID uuid.UUID) (decimal.NullDecimal, error) {
	ret := _m.Called(ctx, userID)

	var r0 decimal.NullDecimal
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) decimal.NullDecimal); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.NullDecimal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewOrders provides a mock function with given fields: ctx
func (_m *MockUseCase) GetNewOrders(ctx context.Context) ([]*entity.Order, error) {
	ret := _m.Called(ctx)

	var r0 []*entity.Order
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOrders provides a mock function with given fields: ctx, userID
func (_m *MockUseCase) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]*entity.Order, error) {
	ret := _m.Called(ctx, userID)

	var r0 []*entity.Order
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetOrderAccrualAndStatus provides a mock function with given fields: ctx, orderID, accrual, status
func (_m *MockUseCase) SetOrderAccrualAndStatus(ctx context.Context, orderID uuid.UUID, accrual decimal.NullDecimal, status entity.OrderStatus) error {
	ret := _m.Called(ctx, orderID, accrual, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.NullDecimal, entity.OrderStatus) error); ok {
		r0 = rf(ctx, orderID, accrual, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOrderStatus provides a mock function with given fields: ctx, orderID, status
func (_m *MockUseCase) SetOrderStatus(ctx context.Context, orderID uuid.UUID, status entity.OrderStatus) error {
	ret := _m.Called(ctx, orderID, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.OrderStatus) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
