// Code generated by mockery v2.10.0. DO NOT EDIT.

package accrual

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, orderNumber
func (_m *MockReader) Get(ctx context.Context, orderNumber entity.OrderNumber) (*entity.AccrualOrder, error) {
	ret := _m.Called(ctx, orderNumber)

	var r0 *entity.AccrualOrder
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderNumber) *entity.AccrualOrder); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AccrualOrder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderNumber) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
