// Code generated by mockery v2.10.0. DO NOT EDIT.

package withdrawal

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, withdrawal
func (_m *MockWriter) Create(ctx context.Context, withdrawal entity.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
