// Code generated by mockery v2.10.0. DO NOT EDIT.

package withdrawal

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, withdrawal
func (_m *MockRepository) Create(ctx context.Context, withdrawal entity.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSum provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetSum(ctx context.Context, userID uuid.UUID) (decimal.NullDecimal, error) {
	ret := _m.Called(ctx, userID)

	var r0 decimal.NullDecimal
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) decimal.NullDecimal); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(decimal.NullDecimal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockRepository) List(ctx context.Context, userID uuid.UUID) ([]*entity.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	var r0 []*entity.Withdrawal
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Withdrawal)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
