// Code generated by mockery v2.10.0. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thorgnir-go-study/yp-diploma/internal/entity"

	uuid "github.com/gofrs/uuid"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, e
func (_m *MockWriter) Create(ctx context.Context, e entity.User) (uuid.UUID, error) {
	ret := _m.Called(ctx, e)

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) uuid.UUID); ok {
		r0 = rf(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
